apiVersion: v1
kind: Pod
metadata:
  name: go-demo-2
  labels:
    type: stack
spec:
  containers:
  - name: db
    image: mongo:3.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  - name: api-1
    image: vfarcic/go-demo-2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: DB
      value: localhost

  - name: api-2
    image: vfarcic/go-demo-2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: DB
      value: localhost