apiVersion: v1
kind: Pod
metadata:
  name: alpine-env
spec:
  containers:
  - name: alpine
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep"]
    args: ["100000"]
    envFrom:
    - configMapRef:
        name: my-config